### ISSUE TITLE
epic: candle integration - image generation

### ISSUE THREAD

**Issue by francis2tm** [edgenai/edgen#119]
To get to a fully functional Image Generation endpoint, the following is required:

1. Design the API
   - [ ] Design a new Image Generation endpoint interface, since OpenAI does not have one we can mimic. This should be the first step, as everything else depends on this.
2. Implement a backend
   - [ ] Implement a backend using [candle](https://github.com/huggingface/candle) that can at least provide the API's functionality. It doesn't necessarily have to implement the API directly, it can (maybe should) be a fully featured backend similar to [llama.cpp](https://github.com/ggerganov/llama.cpp) or [whisper.cpp](https://github.com/ggerganov/whisper.cpp). It's up to the endpoint implementation later to directly implement the API, not the backend. Image generation example in candle: https://github.com/huggingface/candle/blob/main/candle-examples/examples/stable-diffusion/main.rs
3. Edgen implementation
   - [ ] Define an Image Generation endpoint that follows the API directly and translates the API calls to backend calls. This may be implemented according to the already existing traits LLM and Whisper traits in `edgen_core`.
   - [ ] Implement the model endpoint according to the LLM and Whisper endpoints in `edgen_server`.
   - [ ] Implement the loading and downloading logic for the new model kind in `edgen_server/src/model.rs`.
   - [ ] Implement the new endpoint using the backend. `edgen_server/src/openai_shims.rs` may provide some inspiration.
   - [ ] Implement new server routes for the API and connect it to the endpoint (in `edgen_server/src/routes.rs`).

**Comment by opeolluwa** [comment]
hi @francis2tm  can you assign the issue to me, also, let's have a call to discuss the structure of the codebase later this week
